# Generated by Django 6.0.6 on 2026-06-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('UTILITIES', 'Utilities'), ('SUPPLIES', 'Nail Supplies'), ('MARKETING', 'Marketing'), ('EQUIPMENT', 'Equipment'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
